spring:
  application:
    name: shikiri-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: shikiri-auth
          uri: lb://shikiri-auth
          predicates:
            - Path=/auth/**

        - id: shikiri-account
          uri: lb://shikiri-account
          predicates:
            - Path=/accounts/**

        - id: surprise
          uri: https://www.reddit.com/r/languagelearning/
          
          predicates:
            - Path=/

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator
