spring:
  application:
    name: shikiri-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: shikiri-auth
          uri: lb://shikiri-auth
          predicates:
            - Path=/auth/**

        - id: shikiri-account
          uri: lb://shikiri-account
          predicates:
            - Path=/accounts/**

        - id: surprise
          uri: https://www.reddit.com/r/languagelearning/
          predicates:
            - Path=/

        - id: shikiri-tasks
          uri: lb://shikiri-tasks
          predicates:
            - Path=/tasks/**
        
        - id: shikiri-tool
          uri: lb://shikiri-tool
          predicates:
            - Path=/tools/**

        - id: shikiri-board
          uri: lb://shikiri-board
          predicates:
            - Path=/boards/**

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator,
      ANY /gateway/actuator,
      ANY /tasks/actuator,
      ANY /tools/actuator,
      ANY /boards/actuator,
      ANY /auth/swagger**,
      ANY /accounts/swagger**,
      ANY /tasks/swagger**,
      ANY /tools/swagger**,
      ANY /boards/swagger**,
      ANY /auth/v3**,
      ANY /accounts/v3**,
      ANY /tasks/v3**,
      ANY /tools/v3**,
      ANY /boards/v3**

